### ISSUE TITLE
Can't install / integrity checksum failed

### ISSUE THREAD

**Issue by fabianmu** [satrik/homebridge-bslamp2#6]
Logs below, 

USER: homebridge
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-bslamp2@1.0.4

npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://registry.npmjs.org/napi-thread-safe-callback reason: Invalid response body while trying to fetch https://registry.npmjs.org/napi-thread-safe-callback: sha512-PcB8Rpu/7cdLEdFHvG6BBQpvC0jc5dhgPj6v0cv4uitfFVrVunD2X5sR1t0JiKX1kLuzy59YKvUiW7g0aK5v6g== integrity checksum failed when using sha512: wanted sha512-PcB8Rpu/7cdLEdFHvG6BBQpvC0jc5dhgPj6v0cv4uitfFVrVunD2X5sR1t0JiKX1kLuzy59YKvUiW7g0aK5v6g== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2023-02-12T17_16_28_182Z-debug-0.log

Operation failed. Please review log for details.

This is the Log

0 verbose cli /opt/homebridge/bin/node /opt/homebridge/bin/npm
1 info using npm@8.19.3
2 info using node@v18.13.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 5ms
5 timing config:load:file:/opt/homebridge/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 6ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/var/lib/homebridge/.npmrc Completed in 4ms
10 timing config:load:project Completed in 7ms
11 timing config:load:file:/home/homebridge/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/opt/homebridge/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 3ms
18 timing config:load Completed in 34ms
19 timing npm:load:configload Completed in 36ms
20 timing npm:load:mkdirpcache Completed in 13ms
21 timing npm:load:mkdirplogs Completed in 9ms
22 verbose title npm install homebridge-bslamp2@1.0.4
23 verbose argv "install" "--save" "homebridge-bslamp2@1.0.4"
24 timing npm:load:setTitle Completed in 4ms
25 timing config:load:flatten Completed in 9ms
26 timing npm:load:display Completed in 16ms
27 verbose logfile logs-max:10 dir:/home/homebridge/.npm/_logs
28 verbose logfile /home/homebridge/.npm/_logs/2023-02-12T17_16_28_182Z-debug-0.log
29 timing npm:load:logFile Completed in 15ms
30 timing npm:load:timers Completed in 1ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 97ms
33 timing arborist:ctor Completed in 2ms
34 silly logfile done cleaning log files
35 timing arborist:ctor Completed in 0ms
36 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
37 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
38 timing idealTree:init Completed in 907ms
39 timing idealTree:userRequests Completed in 6ms
40 silly idealTree buildDeps
41 silly fetch manifest homebridge-bslamp2@1.0.4
42 http fetch GET 200 https://registry.npmjs.org/homebridge-bslamp2 330ms (cache revalidated)
43 silly placeDep ROOT homebridge-bslamp2@1.0.4 REPLACE for:  want: 1.0.4
44 silly fetch manifest hap-controller@^0.8.1
45 http fetch GET 200 https://registry.npmjs.org/hap-controller 72ms (cache revalidated)
46 timing idealTree:#root Completed in 494ms
47 silly placeDep node_modules/homebridge-bslamp2 hap-controller@0.8.4 OK for: homebridge-bslamp2@1.0.4 want: ^0.8.1
48 silly fetch manifest @abandonware/noble@1.9.2-19
49 silly fetch manifest debug@^4.3.4
50 silly fetch manifest dnssd@^0.4.1
51 silly fetch manifest fast-srp-hap@^2.0.4
52 silly fetch manifest http-parser-js@^0.5.8
53 silly fetch manifest libsodium-wrappers@^0.7.10
54 silly fetch manifest node-hkdf-sync@^1.0.0
55 silly fetch manifest uuid@^9.0.0
56 http fetch GET 200 https://registry.npmjs.org/node-hkdf-sync 212ms (cache miss)
57 http fetch GET 200 https://registry.npmjs.org/dnssd 233ms (cache miss)
58 http fetch GET 200 https://registry.npmjs.org/fast-srp-hap 243ms (cache miss)
59 http fetch GET 200 https://registry.npmjs.org/http-parser-js 262ms (cache miss)
60 http fetch GET 200 https://registry.npmjs.org/debug 275ms (cache miss)
61 http fetch GET 200 https://registry.npmjs.org/uuid 274ms (cache miss)
62 http fetch GET 200 https://registry.npmjs.org/libsodium-wrappers 400ms (cache miss)
63 http fetch GET 200 https://registry.npmjs.org/@abandonware%2fnoble 1654ms (cache miss)
64 timing idealTree:node_modules/homebridge-bslamp2 Completed in 1667ms
65 silly placeDep node_modules/homebridge-bslamp2 @abandonware/noble@1.9.2-19 OK for: hap-controller@0.8.4 want: 1.9.2-19
66 silly placeDep node_modules/homebridge-bslamp2 debug@4.3.4 OK for: hap-controller@0.8.4 want: ^4.3.4
67 silly placeDep node_modules/homebridge-bslamp2 dnssd@0.4.1 OK for: hap-controller@0.8.4 want: ^0.4.1
68 silly placeDep node_modules/homebridge-bslamp2 fast-srp-hap@2.0.4 OK for: hap-controller@0.8.4 want: ^2.0.4
69 silly placeDep node_modules/homebridge-bslamp2 http-parser-js@0.5.8 OK for: hap-controller@0.8.4 want: ^0.5.8
70 silly placeDep node_modules/homebridge-bslamp2 libsodium-wrappers@0.7.10 OK for: hap-controller@0.8.4 want: ^0.7.10
71 silly placeDep node_modules/homebridge-bslamp2 node-hkdf-sync@1.0.0 OK for: hap-controller@0.8.4 want: ^1.0.0
72 silly placeDep node_modules/homebridge-bslamp2 uuid@9.0.0 OK for: hap-controller@0.8.4 want: ^9.0.0
73 silly fetch manifest napi-thread-safe-callback@^0.0.6
74 silly fetch manifest node-addon-api@^4.3.0
75 silly fetch manifest node-gyp-build@^4.5.0
76 silly fetch manifest @abandonware/bluetooth-hci-socket@^0.5.3-10
77 silly fetch manifest ms@2.1.2
78 silly fetch manifest libsodium@^0.7.0
79 silly fetch manifest vows@0.5.13
80 http fetch GET 200 https://registry.npmjs.org/node-gyp-build 106ms (cache revalidated)
81 http fetch GET 200 https://registry.npmjs.org/ms 106ms (cache revalidated)
82 http fetch GET 200 https://registry.npmjs.org/node-addon-api 145ms (cache revalidated)
83 http fetch GET 200 https://registry.npmjs.org/vows 858ms (cache revalidated)
84 http fetch GET 200 https://registry.npmjs.org/napi-thread-safe-callback 879ms (cache revalidated)
85 http fetch GET 200 https://registry.npmjs.org/libsodium 878ms (cache revalidated)
86 http fetch GET 200 https://registry.npmjs.org/@abandonware%2fbluetooth-hci-socket 1474ms (cache revalidated)
87 timing idealTree:node_modules/homebridge-bslamp2/node_modules/hap-controller Completed in 1556ms
88 silly placeDep node_modules/homebridge-bslamp2/node_modules/@abandonware/noble @abandonware/bluetooth-hci-socket@ OK for: @abandonware/noble@1.9.2-19 want: ^0.5.3-10
89 silly placeDep node_modules/homebridge-bslamp2/node_modules/@abandonware/noble napi-thread-safe-callback@ OK for: @abandonware/noble@1.9.2-19 want: ^0.0.6
90 silly placeDep node_modules/homebridge-bslamp2/node_modules/@abandonware/noble node-addon-api@ OK for: @abandonware/noble@1.9.2-19 want: ^4.3.0
91 silly placeDep node_modules/homebridge-bslamp2/node_modules/@abandonware/noble node-gyp-build@ OK for: @abandonware/noble@1.9.2-19 want: ^4.5.0
92 timing idealTree:node_modules/homebridge-bslamp2/node_modules/@abandonware/noble Completed in 14ms
93 silly placeDep node_modules/homebridge-bslamp2/node_modules/debug ms@ OK for: debug@4.3.4 want: 2.1.2
94 timing idealTree:node_modules/homebridge-bslamp2/node_modules/debug Completed in 4ms
95 timing idealTree:node_modules/homebridge-bslamp2/node_modules/dnssd Completed in 0ms
96 timing idealTree:node_modules/homebridge-bslamp2/node_modules/fast-srp-hap Completed in 0ms
97 timing idealTree:node_modules/homebridge-bslamp2/node_modules/http-parser-js Completed in 0ms
98 silly placeDep node_modules/homebridge-bslamp2/node_modules/libsodium-wrappers libsodium@ OK for: libsodium-wrappers@0.7.10 want: ^0.7.0
99 timing idealTree:node_modules/homebridge-bslamp2/node_modules/libsodium-wrappers Completed in 4ms
100 silly placeDep node_modules/homebridge-bslamp2/node_modules/node-hkdf-sync vows@ OK for: node-hkdf-sync@1.0.0 want: 0.5.13
101 timing idealTree:node_modules/homebridge-bslamp2/node_modules/node-hkdf-sync Completed in 3ms
102 timing idealTree:node_modules/homebridge-bslamp2/node_modules/uuid Completed in 0ms
103 timing idealTree:node_modules/homebridge-bslamp2/node_modules/@abandonware/noble/node_modules/@abandonware/bluetooth-hci-socket Completed in 0ms
104 timing idealTree:node_modules/homebridge-bslamp2/node_modules/@abandonware/noble/node_modules/napi-thread-safe-callback Completed in 0ms
105 timing idealTree:node_modules/homebridge-bslamp2/node_modules/@abandonware/noble/node_modules/node-addon-api Completed in 0ms
106 timing idealTree:node_modules/homebridge-bslamp2/node_modules/@abandonware/noble/node_modules/node-gyp-build Completed in 0ms
107 timing idealTree:node_modules/homebridge-bslamp2/node_modules/debug/node_modules/ms Completed in 0ms
108 timing idealTree:node_modules/homebridge-bslamp2/node_modules/libsodium-wrappers/node_modules/libsodium Completed in 0ms
109 timing idealTree:node_modules/homebridge-bslamp2/node_modules/node-hkdf-sync/node_modules/vows Completed in 0ms
110 timing idealTree:buildDeps Completed in 3751ms
111 timing idealTree:fixDepFlags Completed in 5ms
112 timing idealTree Completed in 4674ms
113 timing command:install Completed in 4711ms
114 verbose type invalid-json
115 verbose stack FetchError: invalid json response body at https://registry.npmjs.org/napi-thread-safe-callback reason: Invalid response body while trying to fetch https://registry.npmjs.org/napi-thread-safe-callback: sha512-PcB8Rpu/7cdLEdFHvG6BBQpvC0jc5dhgPj6v0cv4uitfFVrVunD2X5sR1t0JiKX1kLuzy59YKvUiW7g0aK5v6g== integrity checksum failed when using sha512: wanted sha512-PcB8Rpu/7cdLEdFHvG6BBQpvC0jc5dhgPj6v0cv4uitfFVrVunD2X5sR1t0JiKX1kLuzy59YKvUiW7g0aK5v6g== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
115 verbose stack     at Response.json (/opt/homebridge/lib/node_modules/npm/node_modules/minipass-fetch/lib/body.js:79:13)
115 verbose stack     at async RegistryFetcher.packument (/opt/homebridge/lib/node_modules/npm/node_modules/pacote/lib/registry.js:99:25)
115 verbose stack     at async RegistryFetcher.manifest (/opt/homebridge/lib/node_modules/npm/node_modules/pacote/lib/registry.js:124:23)
115 verbose stack     at async Promise.all (index 0)
115 verbose stack     at async [buildDepStep] (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1046:5)
115 verbose stack     at async Arborist.buildIdealTree (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
115 verbose stack     at async Promise.all (index 1)
115 verbose stack     at async Arborist.reify (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:154:5)
115 verbose stack     at async Install.exec (/opt/homebridge/lib/node_modules/npm/lib/commands/install.js:145:5)
115 verbose stack     at async module.exports (/opt/homebridge/lib/node_modules/npm/lib/cli.js:78:5)
116 verbose cwd /var/lib/homebridge
117 verbose Linux 5.15.84-v7l+
118 verbose node v18.13.0
119 verbose npm  v8.19.3
120 error code FETCH_ERROR
121 error errno FETCH_ERROR
122 error invalid json response body at https://registry.npmjs.org/napi-thread-safe-callback reason: Invalid response body while trying to fetch https://registry.npmjs.org/napi-thread-safe-callback: sha512-PcB8Rpu/7cdLEdFHvG6BBQpvC0jc5dhgPj6v0cv4uitfFVrVunD2X5sR1t0JiKX1kLuzy59YKvUiW7g0aK5v6g== integrity checksum failed when using sha512: wanted sha512-PcB8Rpu/7cdLEdFHvG6BBQpvC0jc5dhgPj6v0cv4uitfFVrVunD2X5sR1t0JiKX1kLuzy59YKvUiW7g0aK5v6g== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
123 verbose exit 1
124 timing npm Completed in 5094ms
125 verbose unfinished npm timer reify 1676222188547
126 verbose unfinished npm timer reify:loadTrees 1676222188573
127 verbose code 1
128 error A complete log of this run can be found in:
128 error     /home/homebridge/.npm/_logs/2023-02-12T17_16_28_182Z-debug-0.log

**Comment by fabianmu** [comment]
However,

This worked
`homebridge@r:/var/lib/homebridge $ npm install -g homebridge-bslamp2` and I also was able to pair the lamp.
But installing the plugin in homebrige non-global failed as mentioned above

**Comment by fabianmu** [comment]
Nevermind, running `hb-service update-node` also allowed to install the plugin
