### ISSUE TITLE
HomekitControllerError: M4: Error: 2

### ISSUE THREAD

**Issue by spoonie72** [satrik/homebridge-bslamp2#9]
Found MiBedsideLamp2-F5B4
Start pairing
MiBedsideLamp2-F5B4 pairing failed
===========ERROR START===========
HomekitControllerError: M4: Error: 2
    at PairingProtocol.parsePairSetupM4 (/usr/local/lib/node_modules/homebridge-bslamp2/node_modules/hap-controller/lib/protocol/pairing-protocol.js:276:19)
    at HttpClient.finishPairing (/usr/local/lib/node_modules/homebridge-bslamp2/node_modules/hap-controller/lib/transport/ip/http-client.js:198:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HttpClient.pairSetup (/usr/local/lib/node_modules/homebridge-bslamp2/node_modules/hap-controller/lib/transport/ip/http-client.js:223:9)
    at async IPDiscovery.<anonymous> (/usr/local/lib/node_modules/homebridge-bslamp2/bslamp.js:43:25) {
  statusCode: 2
}
============ERROR END============

**Comment by satrik** [comment]
hey, 
without any context I would assume that either the lamp is already paired with a homekit instance or you have used the wrong pin. please also share the full command which you have used to get this output.

**Comment by spoonie72** [comment]
Hi, sorry, first time posting anything here. Lamp removed from homekit, removed from MiHome app, reset holding both bottons. Then added to MiHome to get it on the wifi network. Then I enter bslamp pair "IP address from my router" "homebridge password" 

If finds the lamp, a second later it starts pairing, then MiBedsideLamp2-F5B4 pairing failed etc

**Comment by satrik** [comment]
you need to use the IP and the pairing code from the lamp, not from the router or homebridge :)
